name: deepcool_digital_dart
description: Unofficial GPLv3 Dart CLI for DeepCool Digital devices.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.12.0

executables:
  deepcool-digital-dart: deepcool_digital_dart
